env:
  es6: true
  node: true
  mocha: true
extends: 'eslint:recommended'
rules:
  no-console: 0
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
